<div class='row'>
    <div class='col-md-offset-1'>
        <h1>News</h1>
    </div>
    <div class='row'>
        <div class='col-md-10 col-md-offset-1'>
            <form action='/' method='get' class='form-inline'>
                <div class='form-group input-group'>
                    <span class='input-group-addon'>Search By</span>
                    <select name='search' class='form-control' required >
                        <?php foreach ($searchFields as $key => $field) : ?>
                            <option value='<?= $key ?>' <?= ($this->request->getQuery('search') ?? array_keys($searchFields)[0]) == $key ? 'selected=\'selected\'' : '' ?> ><?= $field ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <div class='form-group input-group'>
                    <span class='input-group-addon'>Value</span>
                    <input class='form-control' type='text' name='value' required value='<?= $this->request->getQuery('value') ?? '' ?>'>
                </div>
                <input class='btn btn-primary' type='submit' value='Search'/>
                <a class='btn btn-default' href='/'>Clear</a>
            </form>
        </div>
    </div>
    </br>
    <div class='row'>
        <div class='col-md-10 col-md-offset-1'>
            <?php if (count($page->items)) : ?>
                <table class='table'>
                    <thead>
                        <tr>
                            <th>
                                <?= $customTags->orderByAnchor('Title', 'title'); ?> 
                            </th>
                            <th>Author</th>
                            <th>
                                <?= $customTags->orderByAnchor('Posted Date', 'createdAt'); ?>
                            </th>
                            <th>
                                <?= $customTags->orderByAnchor('Views Count', 'views'); ?>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($page->items as $new) : ?>
                        <tr class='clickable-row' data-href='/index/postDetails?id=<?= $new->id ?>'>
                            <td><?= $new->title ?></td>
                            <td><?= $new->users->name . ' ' . $new->users->lastName ?></td>
                            <td><?= $new->createdAt ?></td>
                            <td><?= $new->views ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
                <div class='row'>
                    <div class='col-md-10 col-md-offset-1 text-center'>
                        <?= $customTags->pagination($page->last, $page->current) ?>
                    </div>
                </div>              
            <?php else : ?>
                <div class='col-md-offset-1'>
                    <h3>No news to show you rigth now.</h3>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>

