<!DOCTYPE html>
<html lang='en'>
<head>
    <meta charset='UTF-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <meta http-equiv='X-UA-Compatible' content='ie=edge'>
    <?= Phalcon\Tag::getTitle() ?>
    <?= $this->tag->stylesheetLink('/bootstrap/css/bootstrap.css'); ?>
    <?= $this->tag->stylesheetLink('/css/site.css'); ?>
</head>
<body>
    <nav class='navbar navbar-default'>
        <div class='container-fluid'>
            <div class='navbar-header'>
                <button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#bs-example-navbar-collapse-1' aria-expanded='false'>
                    <span class='sr-only'>Menu</span>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                    <span class='icon-bar'></span>
                </button>
                <a class='navbar-brand' href='/'>News App</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class='nav navbar-nav'>
                <?php
                if ($this->session->has('user')) {
                    echo '<li>' . $this->tag->linkTo('index/addPost', 'New Post') . '</li>';
                    echo '<li>' . $this->tag->linkTo('index/myPosts', 'My Posts') . '</li>';
                }
                ?>
                </ul>
                <ul class='nav navbar-nav navbar-right'>
                <?php
                if ($this->session->has('user')) {
                    $user = $this->session->get('user');
                    echo "<li class='navbar-text'>{$user['name']} {$user['lastName']}</li>";
                    echo '<li>' . $this->tag->linkTo('account/logout', 'Logout') . '</li>';
                } else {
                    echo '<li>' . $this->tag->linkTo('account/register', 'Register') . '</li>';
                    echo '<li>' . $this->tag->linkTo('account/login', 'Login') . '</li>';
                }
                ?>
                </ul>
            </div>
        </div>
    </nav>
    <div class='container'>
        <?php echo $this->getContent(); ?>
    </div>
    <?= $this->tag->javascriptInclude('https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js', false); ?>
    <?= $this->tag->javascriptInclude('https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js', false); ?>
    <?= $this->tag->javascriptInclude('js/site.js'); ?>
    <?= $this->tag->javascriptInclude('js/modals.js'); ?>
</body>
</html>